apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hello-go
  template:
    metadata:
      labels:
        name: hello-go
    spec:
      containers:
      - name: hello
        image: 192.168.56.12:5000/hello-jenkins/hello:v1.${env.BUILD_NUMBER}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
      imagePullSecrets:
      - name: pullsecret
---
apiVersion: v1
kind: Service
metadata:
  name: hello-go
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    name: hello-go
