Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/focal64"
    config.vm.provider :virtualbox do |v|
      v.memory = 2048
      v.cpus = 2
  end

  boxes = [
    { :name => "Server-1", :ip => "192.168.56.10" },
    { :name => "Server-2", :ip => "192.168.56.11" },
    { :name => "Server-3", :ip => "192.168.56.12" }
  ]

  boxes.each do |opts|
    config.ssh.insert_key = false
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network :private_network, ip: opts[:ip]
      # Provision all the VMs in parallel using Ansible after last VM is up.
      if opts[:name] == "Server-3"
        config.vm.provision "ansible" do |ansible|
          ansible.inventory_path = "/etc/ansible/hosts"
          ansible.playbook = "playbook.yml"
          ansible.limit = "all"
          ansible.become = true

        end
      end
    end
  end

end
